[build]
builder = "dockerfile"
dockerfilePath = "api/Dockerfile.prod"

[deploy]
startCommand = "apache2-foreground"
healthcheckPath = "/api/v1/articles"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
