services:
  - type: web
    name: cms-backend
    env: docker
    dockerfilePath: ./api/Dockerfile.prod
    dockerContext: ./api
    plan: free
    envVars:
      - key: CORS_ORIGIN
        value: https://ton-frontend.vercel.app   # à mettre à jour après déploiement Vercel
      - key: DATABASE_URL
        fromDatabase:
          name: cms-postgres
          property: connectionString

databases:
  - name: cms-postgres
    plan: free
